version: '3'
services:
  web:
    container_name: scanner_web
    depends_on:
      - db
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: nginx
    links:
        - db
        - redis
    ports:
      - "8000:80"
      - "6001:6001"
    volumes:
      - ./service:/var/www/html
    environment:
      VOLUME: '/var/www/html'
      DOCKER_USER: 'www-data'
      DOCKER_GROUP: 'www-data'
      HOST_USER_ID: 1000
      HOST_GROUP_ID: 1000

  client:
    container_name: scanner_client
    image: nginx:stable-alpine
    volumes:
      - ./client/dist:/usr/share/nginx/html
    ports:
      - "8080:80"

  db:
    container_name: scanner_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restapi
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  redis:
    container_name: scanner_redis
    image: redis:3.2.0
    ports:
      - "6379:6379"
